name: Code Quality

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install flake
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run flake
      run: |
        flake8 pym
